/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AbstractionInsideImport } from './routes/abstraction-inside'
import { Route as AbstractionAroundImport } from './routes/abstraction-around'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const AbstractionInsideRoute = AbstractionInsideImport.update({
  path: '/abstraction-inside',
  getParentRoute: () => rootRoute,
} as any)

const AbstractionAroundRoute = AbstractionAroundImport.update({
  path: '/abstraction-around',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/abstraction-around': {
      id: '/abstraction-around'
      path: '/abstraction-around'
      fullPath: '/abstraction-around'
      preLoaderRoute: typeof AbstractionAroundImport
      parentRoute: typeof rootRoute
    }
    '/abstraction-inside': {
      id: '/abstraction-inside'
      path: '/abstraction-inside'
      fullPath: '/abstraction-inside'
      preLoaderRoute: typeof AbstractionInsideImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abstraction-around': typeof AbstractionAroundRoute
  '/abstraction-inside': typeof AbstractionInsideRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abstraction-around': typeof AbstractionAroundRoute
  '/abstraction-inside': typeof AbstractionInsideRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/abstraction-around': typeof AbstractionAroundRoute
  '/abstraction-inside': typeof AbstractionInsideRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/abstraction-around' | '/abstraction-inside'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/abstraction-around' | '/abstraction-inside'
  id: '__root__' | '/' | '/abstraction-around' | '/abstraction-inside'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbstractionAroundRoute: typeof AbstractionAroundRoute
  AbstractionInsideRoute: typeof AbstractionInsideRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbstractionAroundRoute: AbstractionAroundRoute,
  AbstractionInsideRoute: AbstractionInsideRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/abstraction-around",
        "/abstraction-inside"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/abstraction-around": {
      "filePath": "abstraction-around.tsx"
    },
    "/abstraction-inside": {
      "filePath": "abstraction-inside.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
